const bcrypt = require('bcryptjs');
const { sequelize } = require('../config/database');
const User = require('../models/User');
const Incident = require('../models/Incident');

async function truncateAll() {
  await sequelize.query('TRUNCATE TABLE ratings, assignments, incident_logs, situation_reports, incidents, users RESTART IDENTITY CASCADE;');
}

async function runSeed() {
  try {
    await sequelize.authenticate();
    await truncateAll();

    const hashedPassword = await bcrypt.hash('Password@123', 12);

    const admins = await User.bulkCreate([
      {
        name: 'National Command Admin',
        email: 'admin1@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'ADMIN',
        phone: '+919810000001',
      },
      {
        name: 'State Command Admin',
        email: 'admin2@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'ADMIN',
        phone: '+919810000002',
      },
    ], { returning: true });

    const responders = await User.bulkCreate([
      {
        name: 'Aarav Singh',
        email: 'responder1@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'RESPONDER',
        phone: '+919820000001',
        force_id: 'NDRF-042',
        unit_name: 'NDRF Battalion 4',
        skills: ['MEDICAL', 'WATER_RESCUE'],
        is_available: true,
        is_online: true,
        location: { type: 'Point', coordinates: [77.209, 28.6139] },
      },
      {
        name: 'Isha Menon',
        email: 'responder2@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'RESPONDER',
        phone: '+919820000002',
        force_id: 'FIRE-DEL-12',
        unit_name: 'Delhi Fire Zone 12',
        skills: ['FIRE', 'MEDICAL'],
        is_available: true,
        is_online: true,
        location: { type: 'Point', coordinates: [77.1025, 28.7041] },
      },
      {
        name: 'Rahul Patil',
        email: 'responder3@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'RESPONDER',
        phone: '+919820000003',
        force_id: 'NDRF-011',
        unit_name: 'NDRF Pune Unit',
        skills: ['RESCUE', 'ROPE'],
        is_available: true,
        is_online: false,
        location: { type: 'Point', coordinates: [73.8567, 18.5204] },
      },
      {
        name: 'Neha Das',
        email: 'responder4@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'RESPONDER',
        phone: '+919820000004',
        force_id: 'COAST-GJ-08',
        unit_name: 'Gujarat Coastal Rescue',
        skills: ['WATER_RESCUE', 'BOAT'],
        is_available: true,
        is_online: true,
        location: { type: 'Point', coordinates: [72.5714, 23.0225] },
      },
      {
        name: 'Vikram Reddy',
        email: 'responder5@disaster.gov.in',
        password_hash: hashedPassword,
        role: 'RESPONDER',
        phone: '+919820000005',
        force_id: 'MED-HYD-05',
        unit_name: 'Hyderabad EMS Taskforce',
        skills: ['MEDICAL', 'AMBULANCE'],
        is_available: true,
        is_online: true,
        location: { type: 'Point', coordinates: [78.4867, 17.385] },
      },
    ], { returning: true });

    const citizens = await User.bulkCreate([
      {
        name: 'Priya Sharma',
        email: 'citizen1@example.com',
        password_hash: hashedPassword,
        role: 'CITIZEN',
        phone: '+919830000001',
      },
      {
        name: 'Mohammed Ali',
        email: 'citizen2@example.com',
        password_hash: hashedPassword,
        role: 'CITIZEN',
        phone: '+919830000002',
      },
      {
        name: 'Kavya Nair',
        email: 'citizen3@example.com',
        password_hash: hashedPassword,
        role: 'CITIZEN',
        phone: '+919830000003',
      },
    ], { returning: true });

    await Incident.bulkCreate([
      {
        title: 'Yamuna Flooding Near Ring Road',
        description: 'Water level rising rapidly, families stranded on first floors.',
        category: 'FLOOD',
        urgency: 'CRITICAL',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [77.259, 28.6131] },
        address: 'Ring Road, Delhi',
        landmark: 'ITO Bridge',
        reporter_id: citizens[0].id,
        ai_urgency: 'CRITICAL',
        ai_category: 'FLOOD',
        ai_spam_score: 0.045,
        ai_resources_needed: ['BOAT', 'ROPE', 'MEDICAL_KIT'],
        ai_summary: 'Major floodwaters trapping residents in multi-story blocks.',
        people_reported: 35,
      },
      {
        title: 'Warehouse Fire in Bhiwandi',
        description: 'Large fire spreading across two adjoining warehouses.',
        category: 'FIRE',
        urgency: 'HIGH',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [73.0381, 19.3002] },
        address: 'Bhiwandi Industrial Area, Maharashtra',
        reporter_id: citizens[1].id,
        ai_urgency: 'HIGH',
        ai_category: 'FIRE',
        ai_spam_score: 0.052,
        ai_resources_needed: ['FIRE_ENGINE', 'WATER', 'MEDICAL_KIT'],
        ai_summary: 'Active industrial fire with risk of adjacent structure ignition.',
        people_reported: 18,
      },
      {
        title: 'Building Collapse Reported in Lucknow',
        description: 'Partial collapse after tremors, multiple injuries reported.',
        category: 'EARTHQUAKE',
        urgency: 'CRITICAL',
        status: 'ASSIGNED',
        location: { type: 'Point', coordinates: [80.9462, 26.8467] },
        address: 'Hazratganj, Lucknow',
        reporter_id: citizens[2].id,
        assigned_to: responders[0].id,
        force_id: responders[0].force_id,
        ai_urgency: 'CRITICAL',
        ai_category: 'EARTHQUAKE',
        ai_spam_score: 0.031,
        ai_resources_needed: ['AMBULANCE', 'ROPE', 'MEDICAL_KIT'],
        ai_summary: 'Structural collapse with trapped civilians after seismic activity.',
        people_reported: 22,
      },
      {
        title: 'Medical Emergency at Railway Platform',
        description: 'Multiple passengers unconscious due to suspected gas leak.',
        category: 'MEDICAL',
        urgency: 'HIGH',
        status: 'IN_PROGRESS',
        location: { type: 'Point', coordinates: [88.3639, 22.5726] },
        address: 'Howrah Junction, Kolkata',
        reporter_id: citizens[0].id,
        assigned_to: responders[4].id,
        force_id: responders[4].force_id,
        ai_urgency: 'HIGH',
        ai_category: 'MEDICAL',
        ai_spam_score: 0.066,
        ai_resources_needed: ['AMBULANCE', 'MEDICAL_KIT', 'WATER'],
        ai_summary: 'Potential toxic exposure causing acute collapse symptoms.',
        people_reported: 14,
      },
      {
        title: 'Tourists Stranded on Hill Route',
        description: 'Road blocked by landslide, group needs extraction.',
        category: 'RESCUE',
        urgency: 'HIGH',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [78.0322, 30.3165] },
        address: 'Mussoorie Road, Uttarakhand',
        reporter_id: citizens[1].id,
        ai_urgency: 'HIGH',
        ai_category: 'RESCUE',
        ai_spam_score: 0.041,
        ai_resources_needed: ['ROPE', 'FOOD_PACK', 'WATER'],
        ai_summary: 'Landslide blockage isolating travelers in elevated terrain.',
        people_reported: 12,
      },
      {
        title: 'Temporary Shelter Required After Cyclone',
        description: 'Village homes damaged, families need immediate tents.',
        category: 'SHELTER',
        urgency: 'MODERATE',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [85.8245, 20.2961] },
        address: 'Puri district, Odisha',
        reporter_id: citizens[2].id,
        ai_urgency: 'MODERATE',
        ai_category: 'SHELTER',
        ai_spam_score: 0.028,
        ai_resources_needed: ['TENT', 'FOOD_PACK', 'WATER'],
        ai_summary: 'Post-cyclone displacement requiring rapid shelter deployment.',
        people_reported: 47,
      },
      {
        title: 'Food Shortage in Relief Camp',
        description: 'Camp stocks depleted; children and elderly affected.',
        category: 'FOOD',
        urgency: 'MODERATE',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [76.9558, 8.5241] },
        address: 'Kollam Relief Camp, Kerala',
        reporter_id: citizens[0].id,
        ai_urgency: 'MODERATE',
        ai_category: 'FOOD',
        ai_spam_score: 0.021,
        ai_resources_needed: ['FOOD_PACK', 'WATER'],
        ai_summary: 'Relief camp resource depletion with vulnerable populations at risk.',
        people_reported: 60,
      },
      {
        title: 'Flash Flood Near Sabarmati',
        description: 'Vehicles submerged at underpass, drivers trapped.',
        category: 'FLOOD',
        urgency: 'HIGH',
        status: 'ASSIGNED',
        location: { type: 'Point', coordinates: [72.5714, 23.03] },
        address: 'Sabarmati Underpass, Ahmedabad',
        reporter_id: citizens[1].id,
        assigned_to: responders[3].id,
        force_id: responders[3].force_id,
        ai_urgency: 'HIGH',
        ai_category: 'FLOOD',
        ai_spam_score: 0.053,
        ai_resources_needed: ['BOAT', 'ROPE', 'AMBULANCE'],
        ai_summary: 'Rapid flooding causing vehicle entrapment in low-lying roadway.',
        people_reported: 11,
      },
      {
        title: 'Residential Fire in Hyderabad',
        description: 'Apartment fire on fourth floor, smoke in corridors.',
        category: 'FIRE',
        urgency: 'HIGH',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [78.4744, 17.366] },
        address: 'Ameerpet, Hyderabad',
        reporter_id: citizens[2].id,
        ai_urgency: 'HIGH',
        ai_category: 'FIRE',
        ai_spam_score: 0.047,
        ai_resources_needed: ['FIRE_ENGINE', 'AMBULANCE', 'ROPE'],
        ai_summary: 'Mid-rise residential fire with heavy smoke propagation risk.',
        people_reported: 26,
      },
      {
        title: 'Unverified Distress Call',
        description: 'Caller reported a collapse but gave conflicting details.',
        category: 'OTHER',
        urgency: 'MODERATE',
        status: 'OPEN',
        location: { type: 'Point', coordinates: [72.8777, 19.076] },
        address: 'Dadar, Mumbai',
        reporter_id: citizens[0].id,
        ai_urgency: 'MODERATE',
        ai_category: 'OTHER',
        ai_spam_score: 0.611,
        ai_resources_needed: ['MEDICAL_KIT'],
        ai_summary: 'Low-confidence report flagged for operator verification.',
        people_reported: 2,
      },
    ]);

    console.log(`Seed complete: ${admins.length} admins, ${responders.length} responders, ${citizens.length} citizens, 10 incidents`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

runSeed();
