// ═══════════════════════════════════════════════════
// SituationReport Model — AI-Generated Sitreps
// ═══════════════════════════════════════════════════
//
// Generated by the AI service every 15 minutes via cron.
// Contains a natural language military-style situation
// report plus a JSONB snapshot of KPIs at that moment.
//
// Pushed to admin clients via WebSocket 'sitrep:new' event.
// ═══════════════════════════════════════════════════

const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/database');

const SituationReport = sequelize.define('situation_reports', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },

  zone: {
    type: DataTypes.STRING(100),
    allowNull: true,
    comment: 'Geographic zone this report covers',
  },

  report_text: {
    type: DataTypes.TEXT,
    allowNull: false,
    comment: 'AI-generated natural language situation report',
  },

  stats: {
    type: DataTypes.JSONB,
    allowNull: true,
    defaultValue: {},
    comment: 'Snapshot of KPIs at generation time',
  },
}, {
  timestamps: true,
  underscored: true,
  tableName: 'situation_reports',
  updatedAt: false,  // Reports are immutable snapshots
  indexes: [
    { fields: ['zone'] },
    { fields: ['created_at'] },
  ],
});

module.exports = SituationReport;
